# Default values for librechat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod

autoscaling:
  enabled: true
  maxReplicas: 5

mongodb:
  persistence:
    size: 50Gi
