apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "librechat.fullname" . }}-env
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
data:
  DOMAIN_CLIENT: "https://{{ .Values.environment }}.librechat.svarm.de"
  DOMAIN_SERVER: "https://{{ .Values.environment }}.librechat.svarm.de"
  MONGO_URI: "mongodb://{{ include "librechat.fullname" . }}-mongodb:{{ .Values.mongodb.service.ports.mongodb }}/LibreChat"
{{- range $key, $val := .Values.config.env }}
  {{ $key }}: {{ $val | quote }}
{{- end }}