apiVersion: v1
kind: Secret
metadata:
  name: librechat
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  CREDS_KEY: {{ .Values.secrets.CREDS_KEY | quote }}
  CREDS_IV: {{ .Values.secrets.CREDS_IV | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.JWT_REFRESH_SECRET | quote }}
  MEILI_MASTER_KEY: {{ .Values.secrets.MEILI_MASTER_KEY | quote }}