name: Package and Push Helmchart


on:
  push:
    branches: [main, develop]

jobs:
  package-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Login to registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Add Bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
  
      - name: helm package
        run: |
          helm dependency build librechat-chart
          helm package librechat-chart --destination .
 

      - name: helm push
        if: ${{ github.event_name == 'push' }}
        run: |
          CHART_FILE=$(ls *.tgz | head -n 1)
          helm push "$CHART_FILE" oci://ghcr.io/${{ github.repository_owner }}/charts